# Generated by Django 4.0 on 2022-01-19 21:35

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('filter_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('format_spec', models.JSONField(verbose_name='Format specification')),
                ('order_ascending', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CTFG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_by_default', models.BooleanField(default=True)),
                ('order_in_chart_type', models.IntegerField()),
                ('chart_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_types.charttype')),
                ('filter_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter_groups.filtergroup')),
            ],
        ),
        migrations.AddField(
            model_name='charttype',
            name='filter_groups',
            field=models.ManyToManyField(through='chart_types.CTFG', to='filter_groups.FilterGroup'),
        ),
        migrations.AddField(
            model_name='charttype',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AddConstraint(
            model_name='ctfg',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('chart_type', 'order_in_chart_type'), name='unique_ctfg_charttype_order'),
        ),
    ]
