# Generated by Django 4.0 on 2022-03-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_groups', '0001_initial'),
        ('chart_types', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charttype',
            name='filter_groups',
        ),
        migrations.AddField(
            model_name='charttype',
            name='filter_groups',
            field=models.ManyToManyField(to='filter_groups.FilterGroup'),
        ),
        migrations.DeleteModel(
            name='CTFG',
        ),
    ]
