# Generated by Django 4.0 on 2022-03-17 03:25

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('chart_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filter_spec', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('main', 'Main'), ('side', 'Side')], default='side', max_length=10)),
                ('order_in_game_and_kind', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('chart_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_groups.chartgroup')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ladder',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('game', 'kind', 'order_in_game_and_kind'), name='unique_game_kind_order'),
        ),
    ]
