# Generated by Django 4.0 on 2022-12-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_old_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Admin'), (2, 'Mod')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
