# Generated by Django 4.0 on 2022-06-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_old_categories', '0001_initial'),
        ('forum_old_forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='forums', to='forum_old_categories.category'),
        ),
    ]
