# Generated by Django 4.0 on 2022-12-25 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_old_topics', '0002_topic_has_poll_topic_importance_topic_is_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum_old_topics.topic')),
            ],
        ),
    ]
