# Generated by Django 4.0 on 2021-12-22 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order_in_group', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('chart_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='chart_groups.chartgroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='chart',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('chart_group'), django.db.models.expressions.F('order_in_group'), name='unique_chart_group_order'),
        ),
    ]
