# Generated by Django 4.0 on 2022-01-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_types', '0001_initial'),
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='chart_types.charttype'),
            preserve_default=False,
        ),
    ]
