# Generated by Django 4.0 on 2022-01-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filter_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numeric_value', models.IntegerField(null=True)),
                ('usage_type', models.CharField(choices=[('choosable', 'Choosable'), ('implied', 'Implied')], default='choosable', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('filter_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter_groups.filtergroup')),
                ('outgoing_filter_implications', models.ManyToManyField(related_name='incoming_filter_implications', to='filters.Filter')),
            ],
        ),
    ]
