# Generated by Django 4.0 on 2022-04-22 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0002_chart_chart_type'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=200)),
                ('charts', models.ManyToManyField(related_name='chart_tags', to='charts.Chart')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
