# Generated by Django 4.0 on 2022-12-25 02:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_old_polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('vote_count', models.IntegerField()),
                ('option_number', models.PositiveIntegerField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_old_polls.poll')),
            ],
        ),
        migrations.AddConstraint(
            model_name='polloption',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('poll'), django.db.models.expressions.F('option_number'), name='unique_poll_option_number'),
        ),
    ]
