# Generated by Django 4.0 on 2022-12-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_old_posts', '0002_rename_text_to_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
