# Generated by Django 4.0 on 2022-05-31 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_old_forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='forum_old_forums.forum')),
            ],
        ),
    ]
