# Generated by Django 4.0 on 2022-06-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_old_topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='has_poll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Sticky'), (2, 'Announcement')], default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unlocked'), (1, 'Locked'), (2, 'Moved')], default=0),
        ),
    ]
